#!/bin/sh
# Alternate version of randompassword that also generates symbols.

N=$1
if [ -z $1 ]
then
N=20
fi
P=$(tr -cd "A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+="</dev/urandom|fold -w$N|head -n1)
echo $P
echo -n $P|xclip -sel clip>/dev/null

