#!/bin/sh
eval N=\${$#}
if [ $N =~ ^[0-9]+$ ]
then
N=20
fi
R="[:alnum]"
show_help() {
cat << EOF
Usage: ${0##*/} [-hv] [-f OUTFILE] [FILE]...
Do stuff with FILE and write the result to standard output. With no FILE
or when FILE is -, read standard input.

    -h          display this help and exit
    -f OUTFILE  write the result to OUTFILE instead of standard output.
    -v          verbose mode. Can be used multiple times for increased
                verbosity.
EOF
}
while getopts hvf: opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        s)  R="A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+=";;
        *) break
    esac
done
P=$(tr -cd $R</dev/urandom|fold -w$N|head -n1)
echo $P
echo -n $P|xclip -sel clip>/dev/null
