#!/bin/sh
eval N=\${$#}
if [ $N =~ ^[0-9]+$ ]
then
N=20
fi
R="[:alnum]"
while :; do
case $1 in
h)cat<<EOF $0 [-sh] EOF;;
s)R="A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+=";;
*)break
esac
shift
done
P=$(tr -cd $R</dev/urandom|fold -w$N|head -n1)
echo $P
echo -n $P|xclip -sel clip>/dev/null
